## Chapter 3 Numpy

In [1]:
import numpy as np

In [32]:
a = np.array([[1.3, 2.2], [2.3, 4.2]], dtype=int32)
type(a)

NameError: name 'int32' is not defined

In [27]:
a.dtype

dtype('complex128')

In [28]:
a.shape

(2, 2)

In [29]:
a.size

4

In [30]:
a.ndim

2

In [31]:
a

array([[ 1.3+0.j,  2.2+0.j],
       [ 2.3+0.j,  4.2+0.j]])

In [36]:
c = np.zeros((3,3))

In [37]:
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [40]:
d = np.arange(10)

In [41]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [45]:
np.arange(0, 3, 0.5).reshape(2,3)

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5]])

In [47]:
np.linspace(0, 100, 15).reshape(5, 3)

array([[   0.        ,    7.14285714,   14.28571429],
       [  21.42857143,   28.57142857,   35.71428571],
       [  42.85714286,   50.        ,   57.14285714],
       [  64.28571429,   71.42857143,   78.57142857],
       [  85.71428571,   92.85714286,  100.        ]])

In [48]:
e = np.arange(5)

In [49]:
e + 3

array([3, 4, 5, 6, 7])

In [50]:
e

array([0, 1, 2, 3, 4])

In [51]:
e * 2

array([0, 2, 4, 6, 8])

In [52]:
e + e

array([0, 2, 4, 6, 8])

In [53]:
np.sin(e)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [55]:
e * np.cos(e)

array([ 0.        ,  0.54030231, -0.83229367, -2.96997749, -2.61457448])

In [59]:
np.arange(9).reshape(3,3) + np.ones((3,3))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [61]:
A = np.arange(3).reshape(1,3)

In [62]:
B = np.ones((3,1))

In [63]:
A

array([[0, 1, 2]])

In [64]:
B

array([[ 1.],
       [ 1.],
       [ 1.]])

In [65]:
np.dot(A, B)

array([[ 3.]])

In [66]:
A * B

array([[ 0.,  1.,  2.],
       [ 0.,  1.,  2.],
       [ 0.,  1.,  2.]])

In [67]:
e

array([0, 1, 2, 3, 4])

In [68]:
e += 10

In [69]:
e

array([10, 11, 12, 13, 14])

In [70]:
np.log(a)

array([[ 0.26236426+0.j,  0.78845736+0.j],
       [ 0.83290912+0.j,  1.43508453+0.j]])

In [71]:
np.sqrt(a)

array([[ 1.14017543+0.j,  1.48323970+0.j],
       [ 1.51657509+0.j,  2.04939015+0.j]])

In [72]:
a.sum()

(10+0j)

In [73]:
e.sum()

60

In [74]:
e.min()

10

In [75]:
e.max()

14

In [76]:
e.mean()

12.0

In [77]:
e.std()

1.4142135623730951

In [81]:
e[2]

12

In [82]:
e[-2]

13

In [83]:
e

array([10, 11, 12, 13, 14])

In [84]:
e[2:5]

array([12, 13, 14])

In [85]:
e[2:5] = [2,3,4]

In [86]:
e

array([10, 11,  2,  3,  4])

In [87]:
a

array([[ 1.3+0.j,  2.2+0.j],
       [ 2.3+0.j,  4.2+0.j]])

In [88]:
for i in a.flat:
    print(i)

(1.3+0j)
(2.2+0j)
(2.3+0j)
(4.2+0j)


In [89]:
for row in a:
    print(row)

[ 1.3+0.j  2.2+0.j]
[ 2.3+0.j  4.2+0.j]


In [90]:
for row in a:
    for i in row:
        print(i)

(1.3+0j)
(2.2+0j)
(2.3+0j)
(4.2+0j)


In [92]:
np.apply_along_axis(np.mean, axis=0, arr=a)

array([ 1.8+0.j,  3.2+0.j])

In [93]:
np.apply_along_axis(np.mean, axis=1, arr=a)

array([ 1.75+0.j,  3.25+0.j])

In [94]:
A = np.random.random((4, 4))

In [95]:
A

array([[ 0.55104004,  0.39107773,  0.45452553,  0.60521445],
       [ 0.71604929,  0.88728972,  0.02685083,  0.76317892],
       [ 0.73089721,  0.78952548,  0.6929465 ,  0.24257993],
       [ 0.35874989,  0.09504847,  0.60221834,  0.58811876]])

In [96]:
A <= 0.5

array([[False,  True,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True,  True, False, False]], dtype=bool)

In [97]:
A[A < 0.5]

array([ 0.39107773,  0.45452553,  0.02685083,  0.24257993,  0.35874989,
        0.09504847])

In [98]:
A

array([[ 0.55104004,  0.39107773,  0.45452553,  0.60521445],
       [ 0.71604929,  0.88728972,  0.02685083,  0.76317892],
       [ 0.73089721,  0.78952548,  0.6929465 ,  0.24257993],
       [ 0.35874989,  0.09504847,  0.60221834,  0.58811876]])

In [100]:
A.shape = (8,2)

In [101]:
A

array([[ 0.55104004,  0.39107773],
       [ 0.45452553,  0.60521445],
       [ 0.71604929,  0.88728972],
       [ 0.02685083,  0.76317892],
       [ 0.73089721,  0.78952548],
       [ 0.6929465 ,  0.24257993],
       [ 0.35874989,  0.09504847],
       [ 0.60221834,  0.58811876]])

In [102]:
A.ravel()

array([ 0.55104004,  0.39107773,  0.45452553,  0.60521445,  0.71604929,
        0.88728972,  0.02685083,  0.76317892,  0.73089721,  0.78952548,
        0.6929465 ,  0.24257993,  0.35874989,  0.09504847,  0.60221834,
        0.58811876])

In [103]:
A

array([[ 0.55104004,  0.39107773],
       [ 0.45452553,  0.60521445],
       [ 0.71604929,  0.88728972],
       [ 0.02685083,  0.76317892],
       [ 0.73089721,  0.78952548],
       [ 0.6929465 ,  0.24257993],
       [ 0.35874989,  0.09504847],
       [ 0.60221834,  0.58811876]])

In [104]:
A.T

array([[ 0.55104004,  0.45452553,  0.71604929,  0.02685083,  0.73089721,
         0.6929465 ,  0.35874989,  0.60221834],
       [ 0.39107773,  0.60521445,  0.88728972,  0.76317892,  0.78952548,
         0.24257993,  0.09504847,  0.58811876]])

In [105]:
A.transpose()

array([[ 0.55104004,  0.45452553,  0.71604929,  0.02685083,  0.73089721,
         0.6929465 ,  0.35874989,  0.60221834],
       [ 0.39107773,  0.60521445,  0.88728972,  0.76317892,  0.78952548,
         0.24257993,  0.09504847,  0.58811876]])

In [106]:
A

array([[ 0.55104004,  0.39107773],
       [ 0.45452553,  0.60521445],
       [ 0.71604929,  0.88728972],
       [ 0.02685083,  0.76317892],
       [ 0.73089721,  0.78952548],
       [ 0.6929465 ,  0.24257993],
       [ 0.35874989,  0.09504847],
       [ 0.60221834,  0.58811876]])

In [107]:
A = np.ones((3,3))

In [108]:
B = np.zeros((3,3))

In [110]:
np.vstack((A, B))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [111]:
np.hstack((A, B))

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.]])