In [1]:
import pandas as pd
import numpy as np

In [11]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                        'price': [12.33, 11.44, 33.21, 13.23, 61]})

In [12]:
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  61.00

In [13]:
frame2 = pd.DataFrame({'id': ['pencil', 'pencil', 'ball', 'pen'],
                        'color': ['white', 'red', 'red', 'blck']})

In [14]:
frame2

color      id
0  white  pencil
1    red  pencil
2    red    ball
3   blck     pen

In [15]:
pd.merge(frame1, frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21   blck

In [16]:
frame1 = pd.DataFrame({'id': ['ball', 'pencil', 'pen', 'mug', 'ashtray'],
                       'color': ['white', 'red', 'red', 'black', 'green'],
                       'brand': ['OMG', 'ABC', 'ABC', 'POD', 'POD']})

In [17]:
frame1

brand  color       id
0   OMG  white     ball
1   ABC    red   pencil
2   ABC    red      pen
3   POD  black      mug
4   POD  green  ashtray

In [18]:
frame2 = pd.DataFrame({'id':['pencil', 'pencil', 'ball', 'pen'],
                      'brand': ['OMG', 'POD', 'ABC', 'POD']})

In [19]:
frame2

brand      id
0   OMG  pencil
1   POD  pencil
2   ABC    ball
3   POD     pen

In [20]:
pd.merge(frame1, frame2)

Empty DataFrame
Columns: [brand, color, id]
Index: []

In [22]:
pd.merge(frame1, frame2, on='brand')

brand  color     id_x    id_y
0   OMG  white     ball  pencil
1   ABC    red   pencil    ball
2   ABC    red      pen    ball
3   POD  black      mug  pencil
4   POD  black      mug     pen
5   POD  green  ashtray  pencil
6   POD  green  ashtray     pen

In [23]:
frame2.columns = ['brand', 'sid']

In [24]:
frame2

brand     sid
0   OMG  pencil
1   POD  pencil
2   ABC    ball
3   POD     pen

In [25]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

brand_x  color      id brand_y     sid
0     OMG  white    ball     ABC    ball
1     ABC    red  pencil     OMG  pencil
2     ABC    red  pencil     POD  pencil
3     ABC    red     pen     POD     pen

In [26]:
frame2.columns = ['brand', 'id']
pd.merge(frame1, frame2, on='id', how='outer')

brand_x  color       id brand_y
0     OMG  white     ball     ABC
1     ABC    red   pencil     OMG
2     ABC    red   pencil     POD
3     ABC    red      pen     POD
4     POD  black      mug     NaN
5     POD  green  ashtray     NaN

In [27]:
pd.merge(frame1, frame2, on='id', how='left')

brand_x  color       id brand_y
0     OMG  white     ball     ABC
1     ABC    red   pencil     OMG
2     ABC    red   pencil     POD
3     ABC    red      pen     POD
4     POD  black      mug     NaN
5     POD  green  ashtray     NaN

In [28]:
pd.merge(frame1, frame2, on='id', how='right')

brand_x  color      id brand_y
0     OMG  white    ball     ABC
1     ABC    red  pencil     OMG
2     ABC    red  pencil     POD
3     ABC    red     pen     POD

In [29]:
pd.merge(frame1, frame2, on=['id', 'brand'], how='outer')

brand  color       id
0   OMG  white     ball
1   ABC    red   pencil
2   ABC    red      pen
3   POD  black      mug
4   POD  green  ashtray
5   OMG    NaN   pencil
6   POD    NaN   pencil
7   ABC    NaN     ball
8   POD    NaN      pen

In [31]:
pd.merge(frame1, frame2, left_index=True, right_index=True, how='left')

brand_x  color     id_x brand_y    id_y
0     OMG  white     ball     OMG  pencil
1     ABC    red   pencil     POD  pencil
2     ABC    red      pen     ABC    ball
3     POD  black      mug     POD     pen
4     POD  green  ashtray     NaN     NaN

In [34]:
frame2.columns = ['brand2', 'id2']
frame1.join(frame2)

brand  color       id brand2     id2
0   OMG  white     ball    OMG  pencil
1   ABC    red   pencil    POD  pencil
2   ABC    red      pen    ABC    ball
3   POD  black      mug    POD     pen
4   POD  green  ashtray    NaN     NaN

In [36]:
array1 = np.arange(9).reshape((3,3))

In [37]:
array2 = array1 + 6

In [38]:
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [40]:
np.concatenate([array1, array2], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [42]:
np.concatenate([array1, array2], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
ser1 = pd.Series(np.random.rand(4), index=[1, 2, 3, 4])

In [45]:
ser2 = pd.Series(np.random.rand(4), index=[5, 6, 7, 8])

In [48]:
pd.concat([ser1, ser2])

1    0.146238
2    0.661614
3    0.656964
4    0.390644
5    0.417620
6    0.318488
7    0.706758
8    0.587932
dtype: float64

In [52]:
ser3 = pd.concat([ser1, ser2], axis=1)

In [53]:
pd.concat([ser1, ser3], axis=1, join='inner')

0         0   1
1  0.146238  0.146238 NaN
2  0.661614  0.661614 NaN
3  0.656964  0.656964 NaN
4  0.390644  0.390644 NaN

In [54]:
pd.concat([ser1, ser2], keys=[1,2])

1  1    0.146238
   2    0.661614
   3    0.656964
   4    0.390644
2  5    0.417620
   6    0.318488
   7    0.706758
   8    0.587932
dtype: float64

In [55]:
pd.concat([ser1, ser2], keys=[1,2], axis=1)

1         2
1  0.146238       NaN
2  0.661614       NaN
3  0.656964       NaN
4  0.390644       NaN
5       NaN  0.417620
6       NaN  0.318488
7       NaN  0.706758
8       NaN  0.587932

In [2]:
 ser1 = pd.Series(np.random.rand(5), index=[1,2,3,4,5])

In [3]:
ser1

1    0.003661
2    0.841780
3    0.227897
4    0.368052
5    0.097764
dtype: float64

In [4]:
ser2 = pd.Series(np.random.rand(4), index=[2,4,5,6])

In [5]:
ser2

2    0.238824
4    0.642082
5    0.750341
6    0.834509
dtype: float64

In [6]:
ser1.combine_first(ser2)

1    0.003661
2    0.841780
3    0.227897
4    0.368052
5    0.097764
6    0.834509
dtype: float64

In [7]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['white', 'black', 'red'],
                     columns=['ball', 'pen', 'pencil'])

In [8]:
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [9]:
frame1.stack()

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [10]:
frame1.unstack()

ball    white    0
        black    3
        red      6
pen     white    1
        black    4
        red      7
pencil  white    2
        black    5
        red      8
dtype: int32

In [11]:
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [12]:
del frame1['ball']

In [13]:
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [14]:
frame1.drop('white')

pen  pencil
black    4       5
red      7       8

In [15]:
dframe = pd.DataFrame({'color': ['white', 'white', 'red', 'red', 'white'],
                      'value': [2,1,3,3,2]})

In [16]:
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [17]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [18]:
frame = pd.DataFrame({'item': ['ball', 'mug', 'pen', 'pencil', 'ashtray'],
                     'color': ['white', 'rosso', 'verde', 'black', 'yellow'],
                     'price': [5.56, 4.20, 1.30, 0.56, 2.75]})

In [19]:
frame

color     item  price
0   white     ball   5.56
1   rosso      mug   4.20
2   verde      pen   1.30
3   black   pencil   0.56
4  yellow  ashtray   2.75

In [20]:
newColors = {
    'rosso': 'red',
    'verde': 'green'
}

In [21]:
frame.replace(newColors)

color     item  price
0   white     ball   5.56
1     red      mug   4.20
2   green      pen   1.30
3   black   pencil   0.56
4  yellow  ashtray   2.75

In [22]:
frame

color     item  price
0   white     ball   5.56
1   rosso      mug   4.20
2   verde      pen   1.30
3   black   pencil   0.56
4  yellow  ashtray   2.75

In [23]:
frame = pd.DataFrame({'item': ['ball', 'mug', 'pen', 'pencil', 'ashtray'],
                     'color': ['white', 'red', 'green', 'black', 'yellow']})

In [24]:
frame

color     item
0   white     ball
1     red      mug
2   green      pen
3   black   pencil
4  yellow  ashtray

In [25]:
price = {
    'ball': 5.56,
    'mug': 4.20,
    'bottle': 1.30,
    'scissors': 3.41,
    'pen': 1.30,
    'pencil': 0.56,
    'ashtray': 2.75
}

In [26]:
frame['price'] = frame['item'].map(price)

In [27]:
frame

color     item  price
0   white     ball   5.56
1     red      mug   4.20
2   green      pen   1.30
3   black   pencil   0.56
4  yellow  ashtray   2.75

In [28]:
reindex = {
    0: 'first',
    1: 'second',
    2: 'third',
    3: 'fourth',
    4: 'fifth'
}

In [29]:
frame.rename(reindex)

color     item  price
first    white     ball   5.56
second     red      mug   4.20
third    green      pen   1.30
fourth   black   pencil   0.56
fifth   yellow  ashtray   2.75

In [31]:
recolumn = {
    'item': 'object',
    'price': 'value'
}

In [33]:
frame.rename(index=reindex, columns=recolumn, inplace=True)

In [34]:
frame

color   object  value
first    white     ball   5.56
second     red      mug   4.20
third    green      pen   1.30
fourth   black   pencil   0.56
fifth   yellow  ashtray   2.75

In [35]:
bins = [0, 25, 50, 75, 100]

In [38]:
cat = pd.cut(frame['value'], bins)

In [39]:
cat

first     (0, 25]
second    (0, 25]
third     (0, 25]
fourth    (0, 25]
fifth     (0, 25]
Name: value, dtype: category
Categories (4, object): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [48]:
cat.index.values

array(['first', 'second', 'third', 'fourth', 'fifth'], dtype=object)

In [49]:
cat.value_counts()

(0, 25]      5
(75, 100]    0
(50, 75]     0
(25, 50]     0
Name: value, dtype: int64

In [50]:
cat = pd.cut(frame['value'], 4)

In [51]:
cat

first      (4.31, 5.56]
second     (3.06, 4.31]
third     (0.555, 1.81]
fourth    (0.555, 1.81]
fifth      (1.81, 3.06]
Name: value, dtype: category
Categories (4, object): [(0.555, 1.81] < (1.81, 3.06] < (3.06, 4.31] < (4.31, 5.56]]

In [55]:
pd.qcut(frame['value'][:-1], 2)

first     (2.75, 5.56]
second    (2.75, 5.56]
third     [0.56, 2.75]
fourth    [0.56, 2.75]
Name: value, dtype: category
Categories (2, object): [[0.56, 2.75] < (2.75, 5.56]]

In [56]:
randframe = pd.DataFrame(np.random.randn(1000,3))

In [57]:
randframe

0         1         2
0   -0.787153  1.119377 -0.640130
1    0.096437 -0.676693  0.125997
2    0.024700 -0.978624  1.136418
3    1.175576  0.435506 -0.132660
4    0.383665  0.825161  1.412385
5   -0.745776  1.305913 -1.149818
6    0.288632 -0.420318  0.639177
7   -0.092844 -0.022679 -0.279523
8   -0.235321 -0.441307 -1.816994
9   -0.447837  0.895595  1.298736
10  -0.076978  0.897954  1.016734
11  -1.642646  0.416646 -0.330391
12  -0.475724  0.393092  0.653220
13  -1.028358 -0.339449 -2.163008
14   0.341680 -0.383377  0.098903
15   0.391854 -0.599743 -0.442681
16  -0.260740  0.103807  1.332384
17  -0.417135  0.851000 -2.268085
18  -0.398465  0.512406 -0.738529
19   0.423681 -1.622698  1.652111
20  -0.815653  0.687026 -0.771112
21   0.538202 -0.818415 -0.787728
22   0.183114 -0.024527  0.273288
23  -0.269312  0.320791 -1.172150
24   2.631103 -1.203536  0.258391
25  -0.003238 -0.208208  1.400375
26  -0.306081  0.376205 -1.460950
27   0.006147  0.278171 -0.944147
28  -2.060906  0.300165  0.094308
29   2.483545 -0.287714  0.631894
..        ...       ...       ...
970  0.073290 -0.223199  0.393633
971 -0.272542 -0.019968  0.920100
972  2.372849  0.147967  1.173069
973  0.637920 -0.044116 -1.465296
974 -1.402754 -0.105810 -0.684902
975 -0.132204 -1.640247  1.830869
976  0.638200 -0.212807  0.955845
977 -1.658899 -0.097647 -0.075444
978  0.441078  0.727363 -0.236264
979  0.548041 -0.271956 -0.726735
980  0.159567  0.022031 -1.389228
981 -0.886652  0.613814 -1.234852
982  0.508681 -1.080690 -1.262898
983 -0.017536  0.628960  0.209426
984 -0.620657 -0.266598  0.768354
985 -0.387469 -0.049138 -0.701407
986  1.978478  0.972845 -0.880057
987 -1.078878  1.534772  0.139138
988 -0.545035 -1.655065  0.256747
989  0.728483  0.948533  1.190505
990  1.431427 -0.027181  0.287659
991 -0.462624 -0.383269 -0.258032
992  0.966237 -0.941821 -0.305382
993  0.879534  1.328524  1.315081
994 -0.431563 -0.408797  0.939128
995  1.746554 -1.082258  0.857864
996  0.020175 -2.222753  0.913740
997  0.336344  0.170805 -0.110706
998 -1.261805 -0.757947 -0.478925
999 -1.468677  0.062248 -0.319084

[1000 rows x 3 columns]

In [58]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.009686     0.020120     0.014578
std       1.039572     0.989309     0.994548
min      -3.286486    -3.154171    -3.503013
25%      -0.730805    -0.640891    -0.654245
50%       0.003541     0.036530     0.021377
75%       0.709916     0.715932     0.630017
max       3.008865     3.137795     2.571229

In [59]:
randframe.std()

0    1.039572
1    0.989309
2    0.994548
dtype: float64

In [65]:
randframe[((np.abs(randframe)) > (3*randframe.std())).any(1)]

0         1         2
471 -0.013696  0.877479 -3.503013
544 -0.619009 -3.154171  1.432796
620 -3.286486 -1.040650  0.408702
653  2.060353 -0.263320 -3.395404
793 -0.744379  3.137795 -0.568608

In [66]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))

In [67]:
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [68]:
new_order = np.random.permutation(5)

In [69]:
new_order

array([0, 4, 2, 3, 1])

In [70]:
nframe.take(new_order)

0   1   2   3   4
0   0   1   2   3   4
4  20  21  22  23  24
2  10  11  12  13  14
3  15  16  17  18  19
1   5   6   7   8   9

In [71]:
np.random.randint(0, 100, 4)

array([68, 64, 46, 53])

In [72]:
text = '16 Bolton Avenue , Boston'

In [73]:
text.split(',')

['16 Bolton Avenue ', ' Boston']

In [75]:
[s.strip() for s in text.split(',')]

['16 Bolton Avenue', 'Boston']

In [76]:
strings = ['A+', 'A', 'A-', 'B', 'BB', 'BBB', 'C+']

In [77]:
':'.join(strings)

'A+:A:A-:B:BB:BBB:C+'

In [78]:
'Boston' in text

True

In [79]:
text.find('qwewqe')

-1

In [80]:
text.index('qwewqe')

ValueError: substring not found

In [81]:
text.count('e')

2

In [82]:
text.replace('e', 'AAA')

'16 Bolton AvAAAnuAAA , Boston'

In [83]:
import re

In [84]:
reg = re.compile('\s+')

In [85]:
reg.split(text)

['16', 'Bolton', 'Avenue', ',', 'Boston']

In [86]:
frame = pd.DataFrame({'color': ['white', 'red', 'green', 'red', 'green'],
                     'object': ['pen', 'pencil', 'pencil', 'ashtray', 'pen'],
                     'price1': [5.56, 4.20, 1.30, 0.56, 2.75],
                     'price2': [4.75, 4.12, 1.60, 0.75, 3.15]})

In [87]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [89]:
group = frame['price1'].groupby(frame['color'])

In [90]:
group

In [92]:
group.groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [93]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [94]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

In [95]:
group.count()

color
green    2
red      2
white    1
Name: price1, dtype: int64

In [96]:
ggroup = frame['price1'].groupby([frame['color'], frame['object']])

In [97]:
ggroup.mean()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [105]:
frame[['price1', 'price2']].groupby([frame['color'], frame['object']]).mean().add_prefix('mean_')

mean_price1  mean_price2
color object                           
green pen             2.75         3.15
      pencil          1.30         1.60
red   ashtray         0.56         0.75
      pencil          4.20         4.12
white pen             5.56         4.75

In [104]:
for name, group in frame.groupby('color'):
    print(name)
    print(group)

green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


In [106]:
group = frame.groupby('color')

In [107]:
def range(series):
    return series.max() - series.min()

In [108]:
group['price1'].agg(range)

color
green    1.45
red      3.64
white    0.00
Name: price1, dtype: float64

In [111]:
group['price1'].agg([range, 'mean'])

range   mean
color              
green   1.45  2.025
red     3.64  2.380
white   0.00  5.560

In [112]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [116]:
sums = frame.groupby('color').sum().add_prefix('sum_')

In [117]:
sums

sum_price1  sum_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [118]:
pd.merge(frame, sums, left_on='color', right_index=True)

color   object  price1  price2  sum_price1  sum_price2
0  white      pen    5.56    4.75        5.56        4.75
1    red   pencil    4.20    4.12        4.76        4.87
3    red  ashtray    0.56    0.75        4.76        4.87
2  green   pencil    1.30    1.60        4.05        4.75
4  green      pen    2.75    3.15        4.05        4.75

In [119]:
frame.groupby('color').transform(np.sum).add_prefix('sum_')

sum_object  sum_price1  sum_price2
0        pen        5.56        4.75
1     pencil        4.20        4.12
2     pencil        1.30        1.60
3    ashtray        0.56        0.75
4        pen        2.75        3.15

In [121]:
frame = pd.DataFrame({'color': ['white', 'black', 'white', 'white', 'black', 'black'],
                     'status': ['up', 'up', 'down', 'down', 'down', 'up'],
                     'value1': [12.33, 14.55, 22.34, 27.84, 23.40, 18.33],
                     'value2': [11.23, 31.80, 29.99, 31.18, 18.25, 22.44]})

In [122]:
frame

color status  value1  value2
0  white     up   12.33   11.23
1  black     up   14.55   31.80
2  white   down   22.34   29.99
3  white   down   27.84   31.18
4  black   down   23.40   18.25
5  black     up   18.33   22.44

In [123]:
frame.groupby(['color', 'status']).apply(lambda x: x.max())

color status  value1  value2
color status                              
black down    black   down   23.40   18.25
      up      black     up   18.33   31.80
white down    white   down   27.84   31.18
      up      white     up   12.33   11.23